controllers/client_panier.py
#! /usr/bin/python
# -*- coding:utf-8 -*-
import datetime

from flask import Blueprint
from flask import request, render_template, redirect, abort, flash, session

from connexion_db import get_db
import time;

client_panier = Blueprint('client_panier', __name__, template_folder='templates')


@client_panier.route('/client/panier/add', methods=['POST'])
def client_panier_add():

    id_client = session['id_user']
    id_chaussure = request.form.get('id_chaussure')
    quantite = request.form.get('quantite', 1, type=int)
    db = get_db()
    mycursor = db.cursor()


    if 'id_user' not in session:
        flash('Vous devez être connecté pour ajouter un article au panier.', 'danger')
        print("bizz")
        return redirect('/login')

    # Vérifier le stock avant d'ajouter au panier
    sql = "SELECT stock FROM Chaussure WHERE id_chaussure = %s"
    mycursor.execute(sql, (id_chaussure,))
    chaussure = mycursor.fetchone()
    date_ajout = datetime.date.today()

    if chaussure and chaussure['stock'] >= quantite:
        print("yes")
        # Ajouter au panier ou mettre à jour la quantité si l'article est déjà présent

        # Étape 1: Vérifier l'existence de l'article dans le panier
        sql_existence = "SELECT id_ligne FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s"
        mycursor.execute(sql_existence, (id_client, id_chaussure))
        existing_entry = mycursor.fetchone()

        # Étape 2 et 3: Mise à jour ou insertion basée sur l'existence
        if existing_entry:
            # L'article existe, mise à jour de la quantité
            sql_update = "UPDATE Ligne_panier SET quantite = quantite + %s, date_ajout = %s WHERE id_utilisateur = %s AND id_chaussure = %s"
            mycursor.execute(sql_update, (quantite, date_ajout, id_client, id_chaussure))
        else:
            # L'article n'existe pas, insertion d'un nouvel article
            sql_insert = "INSERT INTO Ligne_panier (quantite, date_ajout, id_utilisateur, id_chaussure) VALUES (%s, %s, %s, %s)"
            mycursor.execute(sql_insert, (quantite, date_ajout, id_client, id_chaussure))

        db.commit()
        # retirer du stock
        sql = """
    UPDATE Chaussure
    SET stock = stock - %s
    WHERE  id_chaussure=%s ;
        """
        mycursor.execute(sql, (quantite, id_chaussure))
        db.commit()
        flash('Article ajouté au panier avec succès.', 'success')
    else:
        flash('Stock insuffisant pour cet article.', 'warning')

    return redirect('/client/article/show')






@client_panier.route('/client/panier/delete', methods=['POST'])
def client_panier_delete():
    id_client = session['id_user']
    id_chaussure = request.form.get('id_chaussure')
    quantite = request.form.get('quantite', 1, type=int)
    mycursor = get_db().cursor()


    # partie 2 : on supprime une déclinaison de l'article
    # id_declinaison_article = request.form.get('id_declinaison_article', None)

    sql_existence = """SELECT 
    id_ligne AS IdLigne
    ,quantite as Quantite
    ,date_ajout as DateAjout
    ,id_utilisateur as Idutilisateur
    ,id_chaussure as IdChaussure 
    FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s"""
    mycursor.execute(sql_existence, (id_client, id_chaussure))
    article_panier = mycursor.fetchone()

    if not (article_panier is None) and article_panier['Quantite'] > 1:
        # Si la quantité de l'article est supérieure à 1, décrémentez-la de 1
        sql = "UPDATE Ligne_panier SET quantite = quantite - 1 WHERE id_utilisateur = %s AND id_chaussure = %s"
        mycursor.execute(sql, (id_client, id_chaussure))
        flash('Une unité de l\'article a été retirée du panier.', 'success')
    else:
        # Si la quantité est à 1, supprimez l'article du panier
        sql = "DELETE FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s"
        mycursor.execute(sql, (id_client, id_chaussure))
        flash('L\'article a été supprimé du panier.', 'success')

    # mise à jour du stock de l'article disponible
    sql = """
    UPDATE Chaussure
    SET stock = stock + %s
    WHERE  id_chaussure=%s ;
        """
    mycursor.execute(sql, (quantite, id_chaussure))

    get_db().commit()
    return redirect('/client/article/show')


@client_panier.route('/client/panier/vider', methods=['POST'])
def client_panier_vider():
    id_client = session['id_user']
    mycursor = get_db().cursor()
    sql = """SELECT 
   id_ligne as IdLigne, 
   quantite as Quantite, 
   date_ajout as DateAjout, 
   id_utilisateur as IdUtilisateur, 
   id_chaussure as IdChaussure 
FROM Ligne_panier 
WHERE id_utilisateur = %s;
"""
    mycursor.execute(sql, (id_client))
    items_panier = mycursor.fetchall()
    print("e",items_panier)
    for items_panier in items_panier:
        id_chaussure= items_panier['IdChaussure']

        sql = ''' DELETE FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s'''
        mycursor.execute(sql, (id_client, id_chaussure))

        quantite = items_panier['Quantite']
        sql = """
            UPDATE Chaussure
            SET stock = stock + %s
            WHERE  id_chaussure=%s ;
                """
        mycursor.execute(sql, (quantite, id_chaussure))
        get_db().commit()
    return redirect('/client/article/show')


@client_panier.route('/client/panier/delete/line', methods=['POST'])
def client_panier_delete_line():
    id_client = session['id_user']
    id_chaussure = request.form.get('id_chaussure')
    mycursor = get_db().cursor()
    sql= """SELECT 
           id_ligne AS IdLigne
           ,quantite as Quantite
           ,date_ajout as DateAjout
           ,id_utilisateur as Idutilisateur
           ,id_chaussure as IdChaussure 
           FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s"""
    mycursor.execute(sql, (id_client, id_chaussure))
    items_panier = mycursor.fetchone()
    # id_declinaison_article = request.form.get('id_declinaison_article')

    sql = ''' DELETE FROM Ligne_panier WHERE id_utilisateur = %s AND id_chaussure = %s'''
    mycursor.execute(sql, (id_client, id_chaussure))
    quantite = items_panier['Quantite']
    sql = """
    UPDATE Chaussure
    SET stock = stock + %s
    WHERE  id_chaussure=%s ;
        """
    mycursor.execute(sql, (quantite, id_chaussure))

    get_db().commit()
    return redirect('/client/article/show')


@client_panier.route('/client/panier/filtre', methods=['POST'])
def client_panier_filtre():
    # test des variables puis
    # mise en session des variables
    mycursor = get_db().cursor()
    filtre_mot = request.form.get('filtre_mot', None)
    filtre_min = request.form.get('filtre_min', None)
    filtre_max = request.form.get('filtre_max', None)
    filter_types = request.form.getlist('filter_types', None)


    if filtre_mot and filtre_mot != "":
        if len(filtre_mot) > 1:
            if filtre_mot.isalpha():
                session['filtre_mot'] = filtre_mot
            else:
                flash(u'votre mot recherché doit uniquement contenir des lettres')
        else:
            if len(filtre_mot == 1):
                flash(u'votre mot rechercher doit etre plus grand')
            else:
                session.pop('filtre_mot', None)
    if filtre_min or filtre_max:
        if filtre_min.isdecimal() and filtre_max.isdecimal():
            if int(filtre_min) < int(filtre_max):
                session['filtre_min'] = filtre_min
                session['filtre_max'] = filtre_max
                message = u'filtre entre : ' + filtre_min + ' et ' + filtre_max
                flash(message, 'alert-success')
            else:
                message = 'min < max'
                flash(message, 'alert-warning')
        else:
            message = 'pas numerique'
            flash(message, 'alert-warning')
    if filter_types and filter_types != []:
        session['filter_types'] = filter_types
        message = 'case selectioner : '
        for case in filter_types:
            message += 'id:' + case + ' '
        flash(message, 'alert-success')




    return redirect('/client/article/show')















@client_panier.route('/client/panier/filtre/suppr', methods=['POST'])
def client_panier_filtre_suppr():
    # suppression  des variables en session
    session.pop('filtre_mot', None)
    session.pop('filtre_min', None)
    session.pop('filtre_max', None)
    session.pop('filter_types', None)
    print("suppr filtre")
    return redirect('/client/article/show')

templates/client/boutique/_filtre.html
<form method="post"  action="/client/panier/filtre"  style="display: inline-block">
    <div class="form-group">
        <input name="filtre_mot"  type="text" placeholder="Recherche" size="10" class="form-control"
               value="{% if session['filtre_mot'] %}{{ session['filtre_mot'] }}{% endif %}"  >
    </div>
   {% if types_chaussure is defined %}
    <div class="form-group">
        <h4>Types articles</h4>
        {% for types_chaussure in types_chaussure %}
        <input type="checkbox" name="filter_types" value="{{ types_chaussure.IdTypeChaussure }}"
               {% set id_item = types_chaussure.IdTypeChaussure | string %}
               {% if session['filter_types'] %}
{#                   {%  if idItem in session['filter_types'] %} checked  {% endif %} #}
                   {{ ' checked ' if (id_item in session['filter_types']) else '' }}
               {% endif %}
{#                https://stackoverflow.com/questions/58433775/how-to-access-the-value-of-each-checkbox-in-a-table-with-flask#}
            >  {{ types_chaussure.LibelleTypeChaussure }}
            <br/>
        {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <h5>Prix :</h5>
         <input name="filtre_min"  type="text" placeholder="min"  size="3"
            value="{% if session['filtre_min'] %}{{ session['filtre_min'] }}{% endif %}" >

       <input name="filtre_max"  type="text" placeholder="max"  size="3"
             value="{% if session['filtre_max'] %}{{ session['filtre_max'] }}{% endif %}" >
    </div>
    <button type="submit" class="btn btn-primary" style="display: inline-block;">Filtrer</button>
</form>
{% if session['filtre_mot'] or session['filtre_max'] or session['filtre_min'] or session['filter_types']%}
<form  action="/client/panier/filtre/suppr"  style="display: inline-block; margin: 5px;"  method="post" >
<button class="btn btn-primary" > Supprimer filtre </button>
</form>
{% endif %}

templates/client/boutique/_panier.html
<div class="col-7">
{% if Ligne_panier | length >= 1 %}
    <h3>Liste des chaussures dans mon panier</h3>
    <table class="table table-hover table-responsive">
        <tr>
            <th style="width: 300px">Nom</th>
            <th style="width: 50px">Quantité</th>
            <th style="width: 50px">Prix</th>
            <th style="width: 100px">Sous-Total</th>
            <th style="width: 400px">Action</th>
        </tr>
        {% for item_panier in Ligne_panier %}
            <tr>
                <td>{{ item_panier.ChaussureId }}
                {% if item_panier.id_couleur is defined and item_panier.id_couleur != None and item_panier.id_couleur > 1 %}
                    <small style="color: #6dcea2">({{ item_panier.libelle_couleur }})</small>
                {% endif %}
                {% if item_panier.id_taille is defined and item_panier.id_taille != None and item_panier.id_taille > 1 %}
                    <small style="color: #d941c2">({{ item_panier.libelle_taille }})</small>
                {% endif %}
                </td>




                <td>{{ item_panier.Quantite }}</td>
                <td>{{ item_panier.ChaussurePrix }}</td>
                <td>{{ "{:,.2f} €".format((item_panier.ChaussurePrix * item_panier.Quantite)) }}</td>
                <td>
                {% if item_panier.ChaussureStock is defined %}
                    {% if item_panier.ChaussureStock > 0 %}
                    <form action="{{ url_for('client_panier.client_panier_add') }}" method="post">
                        <input type="hidden" name="id_chaussure" value="{{item_panier.ChaussureId }}">
                        <input type="number" name="quantite" value="1" min="1">
                         <input type="submit" value="Ajouter au panier">
                        </form>
                    {% endif %}
                {% endif %}
                    <form action="/client/panier/delete"   style="display: inline-block;"  method="post">
                        <input type="hidden" name="id_chaussure" value="{{ item_panier.ChaussureId }}">
                        <button class="btn btn-primary" > - </button>
                    </form>

                    <form action="/client/panier/delete/line"  style="display: inline-block;"  method="post">
                        <input type="hidden" name="id_chaussure" value="{{ item_panier.ChaussureId }}">
                        <button class="btn btn-primary" >Supprimer</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
        {% if validation is defined and validation == 1 %}
            <a href="/client/chaussure/show" class="btn btn-primary" >Continuer ma commande</a>
        {% else %}
        <form action="/client/panier/vider"  style="display: inline-block;"  method="post" >
            <button class="btn btn-primary"  > Éffacer tout </button>
        </form>
        <form action="/client/commande/valide"  style="display: inline-block;"  method="post" >
            <button class="btn btn-primary" > Passer ma commande </button>
        </form>
        {% endif %}
        {% if prix_total %}
        Total à payer : <strong>{{ "{:,.2f} €".format(prix_total) }}</strong>
        {% endif %}

{% endif %}
</div>

templates/client/boutique/declinaison_article.html
{% extends "client/layout_client.html" %}
{% block body %}
   <h5>choix "déclinaison" d'articles</h5> {# {{ declinaisons | pprint }}#}

    <div class="container">
        <div class="row align-self-right">
        <div class="card col-4 mt-4 p-1">
                            <div class="card-body border-dark rounded p-1">
                                <a href="/client/article/details?id_article={{ article.id_article }}" >
                                <h2 class="card-title">
                                    <span style="color: #0b2e13">{{ article.nom }}</span><br>
                                    {{ article.prix }}
                                    €
                                </h2>
                                     {%  if article.image is not none %}
                                        <img class="card-img-top rounded mx-auto d-block"  style="width:100px;height:100px"  src="{{ url_for('static', filename = 'images/')}}{{ article.image }}"  alt="image  de {{ article.nom }}" >
                                    {% else %} <img class="card-img-top rounded mx-auto d-block"   style="width:100px;height:100px"   src="{{ url_for('static', filename='images/no_photo.jpeg')}}"  alt="image  de {{ article.nom }}" >
                                    {% endif %}
                                    <hr>
                                </a>
                            </div>
        </div>

            <ul>
                {% for item_declinaison in declinaisons  %}
                    <li>
                    {% if item_declinaison.id_couleur is defined and  item_declinaison.id_couleur > 1 %}
                        couleur : <stong style="color:{{ item_declinaison.code_couleur }}">{{ item_declinaison.libelle_couleur }}</stong>
                    {% endif %}
                    {% if item_declinaison.id_taille is defined and  item_declinaison.id_taille > 1 %}
                      - taille : <span> {{ item_declinaison.libelle_taille }}</span>
                    {% endif %}
                    {% if item_declinaison.stock is defined and item_declinaison.stock != None %}
                        {% if item_declinaison.stock > 0 %}
                            <form  action="/client/panier/add"  method="post" class="col-2">
                                 <input type="radio" name="id_declinaison_article" value="{{ item_declinaison.id_declinaison_article }}" required>
                                    <small class="text-muted">Stock restant : {{ item_declinaison.stock }}</small>
                                 <div class="input-group">
                                    <button class="btn  btn-success"  id="button-addon1">
                                            <i class="bi bi-cart"></i>
                                        <i class="fas fa-shopping-cart"></i>Ajouter
                                    </button>
                                        <input type="number" id="input-{{ item_declinaison.id_declinaison_article }}" step="1" min="0" max="{{ item_declinaison.stock }}" class="form-control col-2" value="1" name="quantite"  aria-describedby="button-addon1">
                                 </div>
                            </form>
                       {% else %}
                                 <small class="text-muted">article  momentanément indisponible</small>
                        {% endif %}
                        </li>
                      {% endif %}
                    <hr class="col-5">
                {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}

templates/client/boutique/panier_article.html
{#  articles_panier  : tableau de dictionnaires
        * dictionnaire : nom quantite prix article_id [stock]
        *
#}

{% extends "client/layout_client.html" %}
{% block body %}
    <div class="container">
        <div class="row align-self-right">
        {% include('client/boutique/_panier.html') %}
            <div class="col">
              <h3>Les filtres</h3>
              Chaussures dont le nom est composé par :<br>
                 {% include('client/boutique/_filtre.html') %}
            </div>
        </div>

        <div class="bg-light p-3">
            <h1>Les Chaussures</h1>
        </div>

        <div class="row">
                {% for Chaussure in Chaussure  %}
                        <div class="card col-4 mt-4 p-1">
                            <div class="card-body border-dark rounded p-1">
                                <a href="/client/article/details?id_article={{ Chaussure.IdChaussure }}" >
                                <h3 class="card-title">
                                    <span style="color: #0b2e13">{{ Chaussure.NomChaussure }}</span><br>
                                    {{ Chaussure.PrixChaussure }}
                                    €
                                </h3>
                                     {%  if Chaussure.Image is not none %}
                                        <img class="card-img-top rounded mx-auto d-block"  style="width:100px;height:100px"  src="{{ url_for('static', filename = 'Img/imageChaussures/')}}{{ Chaussure.Image }}"  alt="image  de {{ Chaussure.NomChaussure }}" >
                                    {% else %} <img class="card-img-top rounded mx-auto d-block"   style="width:100px;height:100px"   src="{{ url_for('static', filename='Img/imageChaussures/no_photo.jpeg')}}"  alt="image  de {{ Chaussure.NomChaussure }}" >
                                    {% endif %}
                                    <hr>
                                </a>
                                <div class="row">
{# #}                                {% if  Chaussure.Stock is defined and Chaussure.Stock != None %}
{# #}                                    {% if Chaussure.Stock > 0 %}
                                        <form  action="/client/panier/add"  method="post" class="col-5">
                                            <input type="hidden" name="id_chaussure" value="{{ Chaussure.IdChaussure }}">
                                            <div class="input-group">
                                            <button class="btn  btn-success"  id="button-addon1">
                                                <i class="fas fa-shopping-cart">Ajouter</i>
                                            </button>
                                            <input type="number" id="quantite" step="1" min="1" max="{{ Chaussure.Stock }}" class="form-control" value="1" name="quantite"  aria-describedby="button-addon1">
                                            </div>
                                        </form>
{# #}                                    {% endif %}
{# #}                                {% endif %}
                                     <div class="col-2 align-content-end">
                                    {% if Chaussure.liste_envie is defined %}
                                         {%if  Chaussure.liste_envie== 1%}
                                             <a href="/client/envie/add?id_article={{ Chaussure.IdChaussure }}" style="text-decoration: none">💛</a>
                                         {% else %}
                                             <a href="/client/envie/add?id_article={{ article.IdChaussure }}" style="text-decoration: none">🤍</a>
                                         {% endif %}
                                    {% endif %}
                                     </div>
                                </div>
                            </div>
                            <div class="card-footer">
                            {% if Chaussure.Stock is defined and Chaussure.Stock != None %}
                                 {% if Chaussure.Stock > 0 %}
                                    <small class="text-muted">Stock restant : {{ Chaussure.Stock }}</small>
                                 {% else %}
                                    <small class="text-muted">Chaussure  momentanément indisponible</small>
                                 {% endif %}
                                {% if Chaussure.nb_declinaison is defined and Chaussure.nb_declinaison != None %}
                                    ({{ Chaussure.nb_declinaison }} d.)
                                {% endif %}
                                <br>
                            {% endif %}
                            {% if Chaussure.nb_notes is defined %}
                                {% if Chaussure.nb_notes > 0 %}
                                 <a  href="/client/article/details?id_article={{ Chaussure.IdChaussure }}" >
                                    <span style="color: #3A7734"> note : {{  "{:,.1f}".format(Chaussure.moy_notes) }}({{ Chaussure.nb_notes }})</span>
                                 </a>
                                {% endif %}
                            {% endif %}
                            {% if Chaussure.nb_avis is defined %}
                                {% if Chaussure.nb_avis > 0 %}
                                 <a href="/client/article/details?id_article={{ Chaussure.IdChaussure }}" >
                                    <span style="color: #3A7734">({{ Chaussure.nb_avis }} avis)</span>
                                 </a>
                                {% endif %}
                            {% endif %}
                            </div>
                        </div>
                {% endfor %}
        </div>
    </div>
{#    {{ Chaussures | pprint }}#}
{% endblock %}

templates/client/boutique/panier_validation_adresses.html
{% extends "client/layout_client.html" %}
{% block body %}
    <div class="container">
        <div class="row align-self-right">
            {% include('client/boutique/_panier.html') %}
        </div>
        <div class="row">
             <br>
            <a href="/client/coordonnee/show" class="btn btn-secondary mt-5 col-2"> ajouter une adresse (livrable 2)</a>
            <form action="/client/commande/add"  style="display: inline-block;"  method="post" >
            {% if adresses | length > 0 %}
                <br>
                    <h4>Choisisser l'adresse de livraison</h4>
                    <select  name="id_adresse_livraison" name="adresse_livraison" required  class="form-select">
                        <option value="">Sélectionner l'adresse de facturation</option>
                        {% for adresse  in adresses %}

                             <option value="{{ adresse.id_adresse }}"
                             {% if id_adresse_fav != 0 and id_adresse_fav == adresse.id_adresse %}
                                 selected
                             {% endif %}

                             >{{ adresse.nom }} ({{ adresse.code_postal }})
                                 {{ adresse.ville }} - {{ adresse.rue }}
                             {% if id_adresse_fav != 0 and id_adresse_fav == adresse.id_adresse %}
                                 (f)
                             {% endif %}

                             </option>
                        {% endfor %}
                    </select>
                    <br>

                    <h4>Choisisser l'adresse de facturation</h4>
                    adresse de facturation identique <input type="checkbox" name="adresse_identique" value="adresse_identique" id="adresse_identique" onclick="identique()">
                <br>
                    <select  id="id_adresse_facturation" name="id_adresse_facturation" required class="form-select">
                        <option value="">Sélectionner l'adresse de livraison</option>
                        {% for adresse  in adresses %}
                             <option value="{{ adresse.id_adresse }}"
                             {% if id_adresse_fav != 0 and id_adresse_fav == adresse.id_adresse %}
                                 selected
                             {% endif %}
                             >{{ adresse.nom }} ({{ adresse.code_postal }})
                                 {{ adresse.ville }} - {{ adresse.rue }}
                             </option>
                        {% endfor %}
                    </select>
                {%  else %}
                    Il faut une adresse de livraison et de facturation pour valider la commande (livrable 2)
                    <a href="/client/coordonnee/show"  class="btn btn-primary">Ajouter une adresse (livrable 2)</a>
                {% endif %}
                <br>
                <button class="btn btn-primary mt-4" > Passer ma commande </button>
            </form>
        </div>
    </div>

    <script>
    function identique(){
	if(document.getElementById('adresse_identique').checked == true)
        {
        document.getElementById("id_adresse_facturation").style.display = 'none';
        document.getElementById("id_adresse_facturation").required = false;
        }
        else
        {
        document.getElementById("id_adresse_facturation").style.display = 'block';
        document.getElementById("id_adresse_facturation").required = true;
        }
    };
    </script>
{% endblock %}